export const metadata = {
  title: 'Blog Lists',
  description: 'Generated by LotusDev',
}

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
          {children}
      </>
  )
}